trigger:
  batch: true
  branches:
    include:
    - '*'
pr:
  autoCancel: true
  branches:
    include:
      - '*'

stages:
- stage: Build
  jobs:
    - job: Compile
      steps:
        - checkout: self
          clean: true

        - task: NodeTool@0
          inputs:
            versionSpec: '8.11.1'

        - script: yarn install
          displayName: 'Install packages'

        - script: yarn lint
          displayName: 'Lint'
    
        - script: yarn test:ci
          displayName: 'Run unit tests'

        - task: PublishTestResults@2
          condition: succeededOrFailed()
          inputs:
            testResultsFormat: 'JUnit'
            testResultsFiles: '**/junit.xml'
            failTaskOnFailedTests: true

        - task: PublishCodeCoverageResults@1
          condition: succeededOrFailed()
          inputs:
            codeCoverageTool: 'Cobertura'
            summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
            failIfCoverageEmpty: true

        - script: yarn compile
          displayName: 'Compile'

        - task: CopyFiles@2
          inputs:
            Contents: 'package.json'
            TargetFolder: 'artifact'

        - task: CopyFiles@2
          inputs:
            SourceFolder: 'dist/src'
            Contents: '**'
            TargetFolder: 'artifact/src'

        - task: CopyFiles@2
          inputs:
            SourceFolder: 'artifact'
            Contents: '**'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'

        - task: PublishPipelineArtifact@0
          inputs:
            artifactName: 'drop'
            targetPath: '$(Build.ArtifactStagingDirectory)'

    - deployment: Publish
      displayName: 'Publish'
      environment: 'npm'
      dependsOn: 'Compile'
      variables: {packageName: '@develohpanda/fluent-builder', version: '', currentVersion: ''}
      strategy:
        runOnce:
          deploy:
            steps:
            - bash: '.pipelines/pullPackageVersion.sh'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
              failOnStderr: true
              displayName: 'Pull package version'
              
            - task: Npm@1
              displayName: 'npm publish'
              inputs:
                command: publish
                workingDir: '$(System.DefaultWorkingDirectory)/_develohpanda.$(packageName)/drop'
                verbose: false
                publishEndpoint: 'npm@develohpanda'
              condition: "and(succeeded(), ne(variables['version'], variables['currentVersion']))"

            - task: GitHubRelease@0
              displayName: 'Create GitHub Release'
              inputs:
                gitHubConnection: 'github@develohpanda'
                tagSource: manual
                tag: 'v$(version)'
                title: 'v$(version)'
                releaseNotesSource: input
              condition: "and(succeeded(), ne(variables['version'], variables['currentVersion']))"