trigger:
  batch: true
  branches:
    include:
    - '*'
pr:
  autoCancel: true
  branches:
    include:
      - '*'

stages:
- stage: Install
  jobs:
    - job: InstallJob
      steps:
        - checkout: self
          clean: true

        - task: NodeTool@0
          inputs:
            versionSpec: '8.11.1'

        - script: yarn install
          displayName: 'Install packages'

- stage: Test
  jobs:
    - job: Lint
      steps:
        - script: yarn lint
    
    - job: Test
      steps:
        - script: yarn test:ci
          displayName: 'Run unit tests'

        - task: PublishTestResults@2
          condition: succeededOrFailed()
          inputs:
            testResultsFormat: 'JUnit'
            testResultsFiles: '**/junit.xml'
            failTaskOnFailedTests: true

        - task: PublishCodeCoverageResults@1
          condition: succeededOrFailed()
          inputs:
            codeCoverageTool: 'Cobertura'
            summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
            failIfCoverageEmpty: true

- stage: Build
  jobs:
    - job: BuildJob
      steps:
        - script: yarn compile
          displayName: 'Compile'

        - task: CopyFiles@2
          inputs:
            Contents: 'package.json'
            TargetFolder: 'artifact'

        - task: CopyFiles@2
          inputs:
            SourceFolder: 'dist/src'
            Contents: '**'
            TargetFolder: 'artifact/src'

        - task: CopyFiles@2
          inputs:
            SourceFolder: 'artifact'
            Contents: '**'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'

        - task: PublishPipelineArtifact@0
          inputs:
            artifactName: 'drop'
            targetPath: '$(Build.ArtifactStagingDirectory)'

- stage: Publish
  dependsOn: ['Install', 'Test', 'Build']
  condition: "and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))"
  variables:
    packageName: '@develohpanda/fluent-builder'
  jobs:
    - deployment: Publish
      displayName: Publish
      environment: 'npm'
      strategy:
        runOnce:
          deploy:
            steps:
            - bash: '.pipelines/pullPackageVersion.sh'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
              failOnStderr: true
              displayName: 'Pull package version'
